### ISSUE TITLE
Can't covert Zwgr to WGR

### ISSUE THREAD

**Issue by hopium101** [wagerr/wagerr#103]
Wallet Version 2.0.1 Monte Carlo 
UBUNTU 16.04 LTS
Memory 5.6 gb
Intel Core i7 CPU M 620 2.67 ghz
OS type 64-bit
Disk 241gb

Problem:
No matter how i try changing security level and amounts i always get this error: Try to spend with a higher security level to include more coins

Trying to send zwgr to wgr address (security level default=42). Error:

Version 1 zwgr require a security level of 100 to successfully spend.

Trying to send zWgr to Wgr address (security level=100). Error:

Spend Zerocoin failed with status = 11 Message: Try to spend with a higher security level to include more coins.

Also, I get

Spend Zerocoin failed with status = 7 Message: Failed to find coin set amongst held coins with less than maxNumber of spends

Didn't worked:
resetspentzerocoin
--resync
Wallet repair
Resync

I updated my wallet by downloading new wallet and turning it on. I only stake and never had a masternode. 

DEBUG.log file data:
https://pastebin.com/E7iMULJQ
Wagerr.conf file is empty 
I can't find config.log 

![screenshot from 2019-01-07 04-46-25](https://user-images.githubusercontent.com/46441674/50761512-446c5480-1273-11e9-8dcf-682c779cdb51.png)
<img width="477" alt="screenshot from 2019-01-07 04-47-04" src="https://user-images.githubusercontent.com/46441674/50761518-46361800-1273-11e9-94bb-8111a382b71e.png">
<img width="608" alt="screenshot from 2019-01-07 04-46-01" src="https://user-images.githubusercontent.com/46441674/50761519-46361800-1273-11e9-9206-0c7465cd82b4.png">

I have noticed this problem half year ago and now I am starting to become a little annoyed.

**Comment by zeroedge83** [comment]
Hello,

Please refer to the solution here https://github.com/wagerr/wagerr/issues/25 , ensure auto-convert is switched off via options. If you have further issues contact support@wagerr.com
