### ISSUE TITLE
2.0.2 version does not have a -mojave version

### ISSUE THREAD

**Issue by tubbynl** [wagerr/wagerr#109]
Wagerr Core 2.0.2 (Monte Carlo) does not have a mojave version

### Describe the issue
The release says

> macOS High Sierra and macOS Mojave
> 
> Currently there are known issues with the wagerr-2.0.2-osx.dmg release on macOS High Sierra and macOS Mojave. Accordingly, please use the wagerr-2.0.2-osx-*.dmg release if you run either of these operating systems.

### What behavior did you expect?
wagerr-2.0.2-osx-mojave.dmg to be available as described in the version

### What was the actual behavior (provide screenshots if the issue is GUI-related)?
not downloadable

### How reliably can you reproduce the issue, what are the steps to do so?
https://github.com/wagerr/wagerr/releases/download/v2.0.2/wagerr-2.0.2-osx-mojave.dmg
yields a Page-not-found

**Comment by Cryptarchist** [comment]
@tubbynl apologies for the lack of response, this has been resolved.
