### ISSUE TITLE
"Bet" tab makes wallet not respond, spins for 10-15 minutes..

### ISSUE THREAD

**Issue by kjahns** [wagerr/wagerr#110]
Clicking on the "Bet" tab makes the wallet not respond, takes 10-15 minutes to load betting options..  

Not sure if this is the right place to bring up this issue or not, sorry if not..

I cant be the only one with this issue, still love the wallet and use it all the time, just irritating having to wait for betting options to load, any help is appreciated, thanks!

**Comment by kjahns** [comment]
I thought updating to 2.0.2 would resolve the issue..

It did not, still getting the same results.

Windows x64 on Windows 10 machine

**Comment by Cryptarchist** [comment]
@kjahns thanks for raising this issue. We are aware of it and although `v2.0.2` does improve on performance it is not in such a large way that it can always be noticed.

10-15 minutes is a lot longer than I have experienced, but I get the point!

In our upcoming `v2.1.0` release we no longer scan the chain for betting events each time you select the Betting tab and instead cache/store this data locally so we can fetch it a lot more efficiently.

I will leave this issue open until we have a final release for you with the bug resolved!

**Comment by WagerrTor** [comment]
this issue is closed as we have no bet tab anymore in v3, please open new request issue if you still would like to have bet tab.
