### ISSUE TITLE
[Wagerr Core 2.0.2][Multi Monitor] Main window is not displayed

### ISSUE THREAD

**Issue by AtomiclyCursed** [wagerr/wagerr#111]
When clicking Show/Hide from the tray i expected the main window to appear.

No window is shown just the icon appears on the task bar.

100% reproduction, I have been able to do it for a few versions (months) now, was hoping it would be fixed by now but this doesn't appear to have been the case.

Many version latest i have is 2.0.2 64-bit got it from this github page.

Windows 10, i7 3.4Ghz/ 32Gb ram, SSD & HDD (installed on SSD) resolution is  1920x1200 dual monitors

No Idea if this is related but was in debug.log
GUI: setGeometry: Unable to set geometry 5x13+-1279+340 on QWidgetWindow/'QLabelClassWindow'. Resulting geometry:  120x13+-1279+340 (frame: 8, 31, 8, 8, custom margin: 0, 0, 0, 0, minimum size: 0x0, maximum size: 16777215x16777215).

**Comment by WagerrTor** [comment]
this problem can occure if there are problems with resolution, as example if application minimum resolution is larger than display resolution. Can you reproduce it with 1080P (1920x1080)?

**Comment by AtomiclyCursed** [comment]
I have just tried forcing my monitors to 1920x1080 then closing and reopening wagerr and still have the same issue

**Comment by WagerrTor** [comment]
@agalpin can you try current master/v3.0.0rc3?

**Comment by AtomiclyCursed** [comment]
Installing this didn't seem to fix it, but i noticed and tried clicking "Reset Options" in "settings" and after restarting it's working again so maybe it was bad app settings? Anyway thanks it's working again.
