### ISSUE TITLE
Exception: St13runtime_error, ListMintedCoins: cannot create DB cursor

### ISSUE THREAD

**Issue by kyoungrok0517** [wagerr/wagerr#119]
I see the following error if I swap the wallet.dat to mine after clean install.

![image](https://user-images.githubusercontent.com/1051900/53330937-18945380-3933-11e9-88cf-f4a64607fdbf.png)

GUI window running properly.

![image](https://user-images.githubusercontent.com/1051900/53330957-221dbb80-3933-11e9-8d59-192219f8adb6.png)

Swap the wallet.dat with my one, which was running properly so far.

`v2.0.2`, downloaded from the repository.

Windows 10, i7 7700k, HDD

**db.log**
https://pastebin.com/wUqsuXyX

**debug.log**
https://pastebin.com/Q6sQNjcr

**Comment by Cryptarchist** [comment]
@kyoungrok0517 it looks like your `wallet.dat` might be corrupted in some way.

Could try to first backup your `wallet.dat` and then start the client with `-salvagewallet`.
