### ISSUE TITLE
Use Snap rather than PPA for WagerrOS

### ISSUE THREAD

**Issue by ckti** [wagerr/wagerr#129]
Need final version before these can be completed. 

- [x] Raspberry PI
  - [x] update OS and packages
  - [x] install snap
  - [x] install wagerr
- [x] Rock Pi4 (arm/aarch64)
  - [x] update OS and packages
  - [x] install snap
  - [x] install wagerr
- [x] ISO i386
  - [x] update OS and packages
  - [x] install snap
  - [x] install wagerr
- [x] ISO x86-64
  - [x] update OS and packages
  - [x] install snap
  - [x] install wagerr
- [x] VirtualBox i386
  - [x] update OS and packages
  - [x] install snap
  - [x] install wagerr
- [x] VirtualBox i686 x86-64
  - [x] update OS and packages
  - [x] install snap
  - [x] install wagerr
- [x] VirtualBox EFI x86-64
  - [x] update OS and packages
  - [x] install snap
  - [x] install wagerr
- [x] USB i386
  - [x] update OS and packages
  - [x] install snap
  - [x] install wagerr
- [x] USB i686 boot x86_64
  - [x] update OS and packages
  - [x] install snap
  - [x] install wagerr
- [x] USB EFI boot x86_64
  - [x] update OS and packages
  - [x] install snap
  - [x] install wagerr

**Comment by WagerrTor** [comment]
updated main list, added rockpi4

**Comment by ckti** [comment]
am able to install wagerr from snap on first boot .. this minimizes the size of the images as well

**Comment by ckti** [comment]
All updated at https://github.com/wagerr/wagerros/releases
