### ISSUE TITLE
Masternode Setup Guide (Chinese Version)

### ISSUE THREAD

**Issue by Zkffkah** [wagerr/wagerr#13]
I have written an Chinese version of the wagerr masternode setup guide [here](https://shimo.im/docs/qNqNpCAopXs1B5bA/). And it's used widely by the Chinese community and has helped lots of people setting up their masternode.

I think we can included it in the official wiki with an external link or convert it into markdown and put it directly in the wiki to help those who need a guide in Chinese verison. 

What do you think? Thanks

**Comment by WagerrTor** [comment]
thank you very much for sharing. I sadly am not able to verify, I will ask somebody to verify it before we implement it. I Assigned it to the correct person. I want to include the guide directly in masternode.conf (which is partially there). And I was not able to verify/write in chinese and we will try to add all translations and guides directly into the core.

Wagerr team is working on  guides and other informative guides, I guess it is good moment to add your guide.

Once again, thank you for the guide.

**Comment by WagerrTor** [comment]
@zeroedge83 any update on this?

**Comment by zeroedge83** [comment]
looks good @WagerrTor
