### ISSUE TITLE
Need to get regtest chain working for current code base.

### ISSUE THREAD

**Issue by ckti** [wagerr/wagerr#131]
Regtest chain ssegfaults at block 251 on current master.  Need to have this chain working to test cli commands properly.

All you need to reproduce the error is start wagerr in regtest mode and do a generate 251 in the debug console or with wagerr-cli, 

CLI Error is:
Segmentation fault (core dumped) ~/ckti.wagerr/ckti-master-wagerr/src/qt/wagerr-qt -regtest -debug

Debug log shows 

2019-06-04 11:27:23 CreateCoinStake : kernel found
2019-06-04 11:27:23 CreateNewBlock: Failed to detect masternode to pay <- not connected to this)
2019-06-04 11:27:23 CreateCoinStake: attempted staking 1 times

[debug.log](https://github.com/wagerr/wagerr/files/3252097/debug.log)

**Comment by Kokary** [comment]
Failed to detect masternode to pay => This is a warning, not an error, and seems to be unrelated.
I'll try to catch the segfault in the debugger.

**Comment by WagerrTor** [comment]
this issue is resolved in https://github.com/wagerr/wagerr/pull/138 , closing
