### ISSUE TITLE
transfer wgr 

### ISSUE THREAD

**Issue by kiahmed** [wagerr/wagerr#15]
if I transfer wgr token directly from yobit exchange to my master-node wallet , is it gonna work?

**Comment by WagerrTor** [comment]
Hello kiahmed,

I hope I can help you, but I am sorry to tell you that we can not reply any questions about yobit, we have nothing to do with them and I do not recommend this particular exchange to be used at all, especially if you can use DEX and wagerr's official releases.

Please ask yobit support about it. I assume that they as usually did not start this client but that they are on waves network and it actually should mean that their system will not accept wagerr addresses which start with `W`.

I am not using yobit and I do not log in on Yobit and so I am not in position to tell you anything about 3rd party system. **What I wrote is strictly my assumption**.

I will close this ticket as it is not relevant to this project. Feel free to contact wagerr.com support for getting assistance in that question if something does not work.

If there is any reason where you believe that this ticket should be reopened or is not closed, please feel free to reply to it and it will be automatically open.
