### ISSUE TITLE
maternode outpus nothing

### ISSUE THREAD

**Issue by kiahmed** [wagerr/wagerr#18]
### Describe the issue
I was trying to setup masternode following official guideline, but at step 5 it asks to get output with the following command . In my wallet , it returns nothing even thought there is 25k Wgr on two separate transactions. I can put any output in masternode.conf file to start it. Any idea?

15:12:03
￼masternode outputs
15:12:03
￼[
]

#### If so, please list the steps to reproduce below:
1. go to console 
2. type masternode outputs
3.

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of Wagerr Core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package.

### Machine specs:
- OS: win 10 pro
- CPU: 4 ghz
- RAM: 16 gb
- Disk size:
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log`, `db.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by WagerrTor** [comment]
Hello,

I would just assume that you either did something wrongly or you tried that command before your transaction got enough confirmations to be visible.

can you post txid's of your transactions with 25k?

**Comment by kiahmed** [comment]
go it fixed
