### ISSUE TITLE
Wagerr core wallet _ Problems with converting to zWGR

### ISSUE THREAD

**Issue by Kekcoed** [wagerr/wagerr#20]
Hello! 

I have troubles with wagerr core wallet.  Now i try to explain.
1)Firstly i download wagerr core, then sync it. It was first released version. 
2) My WGR coins were on wagerr.com -  15555 coins. I have moved them to wagerr core wallet successfully. 
3) Then i try to convert 5 WGR to zWGR. It was my first operation on this wallet after deposit was made. In privacy tab i press "mint zerocoin". Then i go to wallet overview tab - it was 5 zWGR with status "unconfirmed". 
4) I returned in privacy tab and press button "Reset". I dont know exactly what this button do but think that it could return 5 zWGR to WGR balance. But as a reslut - 5 coins disappeared both from zWGR and WGR balance. 
5) Coins disappeared after i press button "reset". Next i try to mint 100 zWGR. I go in privacy tab field 100coins and press "mint zerocoin". Then i go to wallet overview tab  - it was 100 zWGR with status "unconfirmed". I wait and got it. 
6) For turning off automatic minting user should insert:
zeromint=0
enablezeromint=0
staking=0

I forget to do it  and suddenly i see that 1000coins became minting. I press "Reset". I dont want 1000coins to be minted. But after pressing Reset - this coins also disappeared. Firstly my wallet have 15555 coins. Now it lost totally 1005 coins. 
7) I have contacted to wagerr supports, 4 days discussing but no result. They cant help me. The last message from them:
"Then you will need a developer to help you, please make an issue request on github, explaining everything in detail. As zerocoin is not deterministic there is a chance it might not be recoverable.  
The link is here. https://github.com/wagerr/wagerr/issues . Please continue the discussion there" 

So i write here and hope for help, because i dont want to lose 1005 coins. 
I can provide all information you need (screens, TXids and others). 
Attached 2 screens - on first you can see my total balance (14548 instead of 15555), on second screen you can see all transactions that were on my wallet - i have not send coins to any other wallets, there were only converting  between WGR and zWGR. 

How to return my 1005 coins back to wallet? Help please. 

![11](https://user-images.githubusercontent.com/36848873/36672948-3e961202-1b12-11e8-9b06-01b289087e0f.jpg)
![22](https://user-images.githubusercontent.com/36848873/36672949-3ebb049a-1b12-11e8-9a93-082aa423dc7b.jpg)

**Comment by WagerrTor** [comment]
Здравствуйте Kekcoed и спасибо за детальную информацию. Я вам по русски пиши потому-что вижу что у вас клиент на русском.

Я думаю вам просто пришлось подождать. Нужно 30 подтверждений для того что-бы было принято.

Я тоже вижу что у вас уже появился баланс на zWGR, так-что я думаю ваша проблема решена.

1. Всегда делайте резервную копию `wallet.dat` и папки `zerocoin` .
2. Когда нажимаете на сброс, вы просто удаляете те трансакции которые не успели войти в блокчейн. 

    - resetspentzerocoin

    > Scan the blockchain for all of the zerocoins that are held in the wallet.dat. Reset mints that are considered spent that did not make it into the blockchain.
    > Requires wallet passphrase to be set with walletpassphrase call.

3. Если не ушло, значит осталось в вашем кошельке, если-же ушло, тогда вы ничего не могли стереть нажимая на сброс. 

    Заново сихронизуйте пожалуйста:
       
      Linux: `wagerr-qt --resync`
      Windows: `wagerr-qt.exe -resync` 

4. Если после сихронизации всё-ещё ничего не будет, пожалуйста попробуйте:

    - resetmintzerocoin <extended_search>
        
    > Scan the blockchain for all of the zerocoins that are held in the wallet.dat. Update any meta-data that is incorrect.
    > Archive any mints that are not able to be found.
    > Arguments:
    > "extended_search"      (bool, optional) Rescan each block of the blockchain looking for your mints. WARNING - may take 30+ minutes!

также как и посмотреть архивированые минты, вошли ли они в блокчейн:

   - reconsiderzerocoins
   > Check archived zWgr list to see if any mints were added to the blockchain.
Requires wallet passphrase to be set with walletpassphrase call.

Я прошу прощения если вам коллеги не адекватно ответили, вам сразу нужно было обратится сюда.

Попробуйте пожалуйста то что я вам написал и скажите нам получилось ли или нет.

**Comment by Kekcoed** [comment]
Здравствуйте, большое спасибо за ваш ответ, в моем случае мне помог  4-ый пункт.
