### ISSUE TITLE
Wagerr Core version v3.1.0-Atlantic City (64-bit) stuck syncing half way

### ISSUE THREAD

**Issue by whittlem** [wagerr/wagerr#207]
I managed to get Wagerr Core version v3.1.0 installed onto my iMac by disabling all security settings! At least it is installed and runs now. The wallet seems to be stuck syncing. It says "Synchronising with network... 42 weeks behind. Scanning block 893208". I've restarted it and it rebuilds the index but then gets stuck at this point again. How do I resolve this? I see there is a "Wallet Repair" option in the menu. Is it safe to run this?

**Comment by zeroedge83** [comment]
Wagerr 4.0 is now released
