### ISSUE TITLE
mainnet sync hung

### ISSUE THREAD

**Issue by kiahmed** [wagerr/wagerr#3]
### Describe the issue
mainnet running with incoming port open , but looks like sync is hung at that block forever. Is that the case for others too? Also, as I mentioned p2p incoming port open but never got any incoming peer.

### Screenshots.

![capture](https://user-images.githubusercontent.com/28849607/36445998-e2e2e174-164d-11e8-89a5-51c9baf0cd63.PNG)

### What version of Wagerr Core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package.

### Machine specs:
- OS:windows 10 pro
- CPU:4 core
- RAM: 32 gb
- Disk size: 200gb
- Disk Type (HD/SDD): ssd

**Comment by flatyoder** [comment]
You aren't the only one. Come join us on the discord or telegram chat. The dev team seems to be making progress, and will be updating us all soon.

**Comment by kiahmed** [comment]
that means its broken again then. would wait for next release

**Comment by Cryptarchist** [comment]
@kiahmed & @flatyoder thank you for your patience, the latest version [1.4.34.1](https://github.com/wagerr/wagerr/releases/tag/v1.4.34.1) will resolve this issue.

If it continues to get stuck, please use `resync` to synchronise the blockchain from scratch.
