### ISSUE TITLE
Wagerr wallet.dat can't be unlocked while password is correct!

### ISSUE THREAD

**Issue by Cedericm** [wagerr/wagerr#36]
Dear

I had an encrypted wallet.dat file which wouldn't let me unlock the wallet. However I was100% sure the password was correct.

I used a copy of my wallet.dat file and used brute force software the find out the password. If I enter my correct password in a dictionary file that the software uses it finds a match. 

So I was certain I had somewhere the correctly encrypted private keys still in my wallet!

After 3 full days of debugging and using several tools + writing my own private key to WIF key converter I was able to restore my locked coins and import my private key back into another wallet.

I think it is important to share this as other people may hit the same issue. I have seen several topisc on the PIVX forum around this. I'll create a website explaining all my steps and provide the nessacary tooling. Of coarse a donation button will be in place :).

Thank you in advance

![image](https://user-images.githubusercontent.com/15143006/37596013-0f540fe8-2b7b-11e8-853c-d28a82bd0173.png)

**Comment by Cedericm** [comment]
Extra info:

I tweaked the pywallet.py script so that I could fake an succesfull pasword match still using my so called wrong password to get other data out.

This resulted in the following:

When i used the site https://www.bitaddress.org and click on show details i enter the field
"Enter Private Key" the value of the json "sec" field.
If I click then on "view details"the tool correctly generates my public key + compressed address.

This shows to me that the generated sec & secret fields are correct. I am so close now I think. The only thing I need now is how to make a transaction with the secret or tweak the https://www.bitaddress.org code to generate a wager like private key en public uncompressed address.
        {
            "addr": "my compressed address", 
            "compressed": true, 
            "encrypted_privkey": "my encrypted kkey", 
            "hexsec": "my hex sec", 
            "pubkey": "my pub key", 
            "reserve": 1, 
            "sec": "my sec", 
            "secret": "my secret"
        },

**Comment by Cedericm** [comment]
Ok in short what I need is Secret key to WIF explained like this : 
https://en.bitcoin.it/wiki/Wallet_import_format 
But now of coarse for Wagerr.

**Comment by Cedericm** [comment]
Ok found out that these are the neede value for the production chian:
private key byte -> 199 -> 0xC7
address byte -> 73 -> 0x49

// Wagerr addresses start with 'W'
base58Prefixes[PUBKEY_ADDRESS] = std::vector<unsigned char>(1, 73);
 // Wagerr script addresses start with '7'
 base58Prefixes[SCRIPT_ADDRESS] = std::vector<unsigned char>(1, 63);
 // Wagerr private keys start with '7' or 'W'
 base58Prefixes[SECRET_KEY] = std::vector<unsigned char>(1, 199);

**Comment by WagerrTor** [comment]
@Cedericm can you check if it is resolved with [version 1.5.0](https://github.com/wagerr/wagerr/releases/tag/1.5.0)

**Comment by Cedericm** [comment]
Hi, I tested it with my old faulty wallet file. The new version still could not unlock it. @WagerrTor

**Comment by sycamoreflux** [comment]
Hello how do you fix this? I'm also sure my passphrase is correct but I can't unlock the wallet.

**Comment by Cedericm** [comment]
Please find me in the off. Wagerr Telegram group as CryptoPatrick. PM me

**Comment by WagerrTor** [comment]
We will write according recovery guides but we have to take care what we write. There are several tools and ways how you can crack a password, according to the screenshot Cedericm used [Bitcoin password recovery tool](https://www.thegrideon.com/bitcoin-password-recovery.html) which is one of many ways to resolve the issue if you lost your pass (I did not test this tool) but its always better to use open source for such purpose, especially if you run windows. 

I will close this issue, feel free to reopen it if you run into the same issue.

**Comment by hknygt** [comment]
Hi Cedericm , 
Did you fix your issue ?
