### ISSUE TITLE
About bip44 coin type

### ISSUE THREAD

**Issue by Zkffkah** [wagerr/wagerr#41]
Hello Team, it seems we didn't register for the coin type in https://github.com/satoshilabs/slips/blob/master/slip-0044.md for bip44. In the source code, it's still the same as pivx, can I know what our coin type is ?

**Comment by WagerrTor** [comment]
No, not registered for now, using sources [defaults](https://github.com/wagerr/wagerr/blob/master/src/chainparams.cpp#L228) until then, we will register as it should have been already done before.

Thanks for reminder.

**Comment by WagerrTor** [comment]
Updated: 
0x80776772

Feel free to reopen if you want to suggest another.

Why 776772? - wgr in HEX is 776772

https://github.com/satoshilabs/slips/pull/343
