### ISSUE TITLE
Corrupted block database detected

### ISSUE THREAD

**Issue by rge17** [wagerr/wagerr#42]
While running 
`/wagerr-1.5.0/bin # ./wagerrd &
Following error is coming;
_Wagerr server starting: Corrupted block database detected. Do you want to rebuild the block database now?_
If you enter yes, it is running continuously without any output. Kept the console as it is for 24 hours with no outcome.

### Expected behavior
Masternode set up failed

### Actual behavior
With wagerr-1.4.34.2 version, masternode was running without issues. With version 1.5.0, the masternode stopped working

### What version of Wagerr Core are you using?
V1.5.0

### Machine specs:
Ubuntu

**Comment by rge17** [comment]
./wagerr-cli getinfo
error: {"code":-28,"message":"Loading block index..."}

Clicking OK in the console is showing OK> command not found

**Comment by WagerrTor** [comment]
In general, for most coins, if you kill your wallet, then your database mostly becomes corrupted. You should always switch your wallets off with `wagerr-cli stop` and wait until it is closed by checking if process is still running, for example this command to view all processes: `ps axfo pid,euser,egroup,args`. If wagerr-cli stop is not working, then you have to kill your wallet and resync/reindex.

To resolve corrupted database, you have to resync/reindex (reindexing is faster). Feel free to reopen if you still have issue with corrupted database.
