### ISSUE TITLE
Wallet GUI does not scale correctly to various resolutions

### ISSUE THREAD

**Issue by DanielMagro97** [wagerr/wagerr#43]
### Describe the issue
The GUI Wallet does not scale correctly on certain resolutions. On my VM Resolution of 1360x763

As you can see, in the send tab, there is plenty of space for the "Send" button, however it is just not displayed. I have also tried removing Coin Control features, however this doesn't show the "Send" button either.
![image](https://user-images.githubusercontent.com/14795178/41542818-1beacc00-7316-11e8-971a-601be9087d59.png)

The same issue is present in the Privacy Tab
![image](https://user-images.githubusercontent.com/14795178/41543791-dcdf5448-7317-11e8-9294-b7dac3744011.png)

I know that funds can be sent via the debug console, but this is not ideal and does offer easy coin control.

### What version of Wagerr Core are you using?
I'm using the latest Release for Linux

### Machine specs:
- OS: Lubuntu 16.04
- CPU: 2 core 
- RAM: 3GB
- Disk size: 25GB
- Disk Type (HD/SDD): HDD

**Comment by WagerrTor** [comment]
Here you have to small resolution, when I run it on some devices connected to old TV which has smaller height than 1080.

If you double click on title bar, you will get out/into fullscreen mode and when you enter fullscreen, your buttons become visible.

**Comment by WagerrTor** [comment]
I closed it, feel free to reopen if you still cant see buttons
