### ISSUE TITLE
Warning - while compiling

### ISSUE THREAD

**Issue by zeroedge83** [wagerr/wagerr#45]
This issue tracker is only for technical issues related to Wagerr Core.
General Wagerr questions and/or support requests and are best directed to the [Wagerr Discord](https://discord.wagerr.com).

### Describe the issue
warnings while compilation

masternodeconfig.cpp:63:37: warning: unknown escape sequence: '\w'
                                     "#When using the multi masternode setup, it is advised to run the wallet with 'masternode=0' as it is not needed anymor
                                     ^
masternodeconfig.cpp:63:37: warning: unknown escape sequence: '\<'
masternodeconfig.cpp:63:37: warning: unknown escape sequence: '\>'
masternodeconfig.cpp:63:37: warning: unknown escape sequence: '\<'
masternodeconfig.cpp:63:37: warning: unknown escape sequence: '\>'

#### If so, please list the steps to reproduce below:
1. compile QT or daemon

**Comment by WagerrTor** [comment]
this is resolved in last versions, I will close it, reopen it if not
