### ISSUE TITLE
No block index available - Having to reindex every time I load wallet.

### ISSUE THREAD

**Issue by Jacks2High** [wagerr/wagerr#59]
Ok so every time I load up the wallet 2.0 I get a no block index available in the bottom left of the screen. The wallet then wont sink. The only solution to this is to rebuild the block index from zero and then its fine until I turn off the wallet and close down my PC. 

All my coins are find and I am still receiving masternode rewards. Unfortunately this has been happening since the 1.5 release. I assumed it was a bug that would be fixed in 2.0 however with the new release the exact same thing happens. I think it is probably a set up issue with my PC - running Windows 7 Pro

I expected the wallet to automatically sync and update from last indexed block. 

No block sinking and having to rebuild from block 0 to fix

Every time I close the wallet and open it again the following day

Monte Carlo - 2.0. Downloaded from github. EXE download and automated install

Windows 7 PC. SSD 500gb

![blockindex](https://user-images.githubusercontent.com/29517472/45474984-5b72be00-b73b-11e8-9e2c-691a5e525107.jpg)

**Comment by WagerrTor** [comment]
Thanks for supplying the issue, this is very old, I will close this one as it is not relevant anymore due to available newer version v2.0.1, feel free to reopen this issue if it is not gone with v2.0.1
