### ISSUE TITLE
Possibly combined masternode ? /Locked WGR

### ISSUE THREAD

**Issue by Nynti** [wagerr/wagerr#60]
**Describe the issue**
Hello , I have just updated my Wallet to 2.0 and it presents 50.000 WGR locked .
And my balance is negative and the total is the exact correct number that I own.
Is this a normal occurrence? 

**Expected behavior**
I would have excepted 25.000 WGR (same as my total ) but 50.000 seems too much. 

**Screenshots** 
![wagger](https://user-images.githubusercontent.com/35430989/45494445-57fa2980-b771-11e8-95a5-e0f915538629.png)

 **Can you reproduce the issue** 
Yes

 **What version of Wagerr Core are you using, where did you get it (website, self-compiled, etc)?** 
-Wagerr Core 2.0.0 (Monte Carlo)

 **What type of machine are you observing the error on (OS/CPU and disk type)?**
<ul>
<li>OS :Windows 7 </li>
<li>CPU : Intel i5 3.30ghz</li>
<li>Ram : 8.00</li>
<li>Disk size : 2To </li>
<li>Disk Type OCZ-AGILITY3 ATA Device </li>
</ul>

 **Any extra information that might be useful in the debugging process.** 

This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

_Thank you in advance for your time._

**Comment by Kokary** [comment]
Thanks for your report, it's also much appreciated that you filled out the issue template.

The fix (https://github.com/wagerr/wagerr/pull/64/commits/affd03910d115b8f201180ab353ceb0c126b573a) will be merged to master soon, and will be included in next update.
