### ISSUE TITLE
Fatal Error Message

### ISSUE THREAD

**Issue by RobertV49** [wagerr/wagerr#61]
About 2 weeks ago my wagerr core wallet shutdown on me. I tried to reopen it and I'm getting a "fatal error message." I have no idea what the issue is or how to fix it. I've updated to the 2.0 wallet, but not luck fixing the issue. Anyone out there can help me? Thanks.
![wagerr](https://user-images.githubusercontent.com/43261779/45532145-8d763580-b7b8-11e8-81d2-b42613bdd22d.png)

**Comment by Cryptarchist** [comment]
@RobertV49 could you please try a `resync` using a v2.0.0 wallet.

If that doesn't solve the problem, if you can find the applicable line/s in your `debug.log` when it crashes it will help us debug the issue.

**Comment by WagerrTor** [comment]
not relevant anymore, v2.0.1 is released long time ago, I will close this one, feel free to open if issue is unresolved with v2.0.1
