### ISSUE TITLE
Possible Security Issue

### ISSUE THREAD

**Issue by ag100** [wagerr/wagerr#63]
I originally opened this issue with Google Docs during the testnet phase, but the bug is still present in production so I'm opening this here at the request of Wagerr email support.  I have only tested on High Sierra, Android and Linux, but this issue is confirmed on all.

Please let me know if you would like details posted below, or if not, how you would prefer to receive them.

**Comment by Kokary** [comment]
Could you please hit me up on Discord? 
Kokary#8814
Thank you!

**Comment by ag100** [comment]
Ack - Will find you tomorrow.  Thanks.

**Comment by ag100** [comment]
FYI - Sent details to support per their request.

**Comment by Kokary** [comment]
Thanks!
