### ISSUE TITLE
Says 'Bet Placed' in notification popup, even when a regular send transaction happens

### ISSUE THREAD

**Issue by sigwo** [wagerr/wagerr#76]
Linux GUI Wagerr Core version v2.0.0-Monte Carlo (64-bit) https://github.com/wagerr/wagerr/blob/0280c6642176f1401f08905fe0e06c969a979cb7/src/qt/bitcoingui.cpp#L1160

**Comment by Kokary** [comment]
Thanks @sigwo! 
Looks like simply wrong ordering, will fix it.

**Comment by Cryptarchist** [comment]
Closed by 7b3ced1d7a878152b14ac25206b8f72dcd30326e.
