### ISSUE TITLE
"masternode start local" return "Not capable masternode: Could not connect to  xxxxx" 

### ISSUE THREAD

**Issue by atenjin** [wagerr/wagerr#8]
### "masternode start local" return "Not capable masternode: Could not connect to  xxxxx" 
vps: 
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 8.2 (jessie)
Release:        8.2
Codename:       jessie

I compile from the source code.
```bash
-->$ ./wagerrd -version
Wagerr Core Daemon version v1.4.34.1-1-ga6176b0-Vegas
```
my wager.conf is like this:
```bash
rpcuser=<user>
rpcpassword=<passwd>
rpcallowip=127.0.0.1
listen=1
server=1
daemon=1
logtimestamps=1
maxconnections=256
# externalip=<ip>
# bind=<ip>
zeromint=0
enablezeromint=0
masternode=1
masternodeaddr=<ip>:55002
masternodeprivkey=<>                        
```
and I have transfer 25000 wgr to the address which is produced from the masternodeprivkey, and import the prikey to the wallet.

I want to start masternode from in the vps.

I guess the mode is "local" which show in the source code.

but when I try 
```bash
wagerr-cli masternode start local 
```
the result is 
``` bash
Not capable masternode: Could not connect to  <ip:port>
```
and the log is 
```bash
2018-02-22 02:22:49 ProcessNewBlock : ACCEPTED in 5 milliseconds with size=503
2018-02-22 02:23:13 CActiveMasternode::ManageStatus() - Checking inbound connection to 'myip:55002'
2018-02-22 02:23:13 CActiveMasternode::ManageStatus() - not capable: Could not connect to 'myip:55002
2018-02-22 02:23:58 Adjusting seesaw at height 7995 with 265 masternodes (without drift: 245) at 1519266238
```
in the source code:
<img width="1073" alt="_20180222105954" src="https://user-images.githubusercontent.com/5023721/36519157-f1f930be-17c4-11e8-8ae8-07b01e9d0973.png">

I think the process return at that point in the img

**so is this a bug or my operation is not the right way?**

I try to run masternode from local(in vps), and in the code the check will reject the local addr?

and it's match for the log.

**Comment by Cryptarchist** [comment]
@JKingdom I just set up a quick tutorial for setting up a remote masternode on a VPS and having your main wallet locally (or another location).

https://github.com/wagerr/wagerr/wiki/Setting-up-a-masternode

Would you mind taking a look to see if that assists you at all?

**Comment by atenjin** [comment]
I have read this tutorial before. 
My question is start masternode just in vps, not from a external node to start masternode.
Through I haven't read all source code, I guess the mechanism is that the other node add the masternode to the global map so that the source node can start self.
But when somebody what to add self to the global masternode map, it would meet this problem(I guess).

ps: I think there is something wrong in this tutorial.
in wagerr.conf
```bash
listen=0
```
I don't thing this is right.
I have try this, and find the vps port 55002 not listen...
I think this "listen" should set "1" as default.

and another thing, follow the tutorial, when run
```bash
wagerr-cli masternode genkey
```
the privkey would not set into the wallet.dat database...(the source code show this)
and the step 3 is useless

if somebody should follow the tutorial, I suggesst changing the step 3 to 
```bash
wagerr-cli importprivkey xxxxx xxx
```
is the right way

**Comment by WagerrTor** [comment]
hello and thanks for submitting the issue as well for nice overview and analysis.

Please look into the issue #6 . My answer there applies here too. Ensure please that your port is open (_55002_).

I will just close this one but feel free to reply here and reopen if the issue is still present.
