### ISSUE TITLE
blockchain sync fails

### ISSUE THREAD

**Issue by kiahmed** [wagerr/wagerr#88]
no matter how I configure blockchain syncing failing either at block 1000 or 1650 . I tried all different ways deleting whole data dir, reindexing, resyncing , downloaded the new release last night but still now luck stops with the following error. I have other older nodes running fine. Any idea whats up? 
**RecalculateZWGRSpent : block 1000...
wagerrd: main.cpp:2582: bool RecalculateWGRSupply(int): Assertion `GetTransaction(prevout.hash, txPrev, hashBlock, true)' failed.
run.sh: line 1:     6 Aborted                 wagerrd -datadir=$APP_DATADIR** 

continue loading the chain successfully

running just daemon

every time

Wagerr 2.0.1

Ubuntu 16.04 in a docker container

**Comment by WagerrTor** [comment]
@kiahmed 
thanks for supplying the issue, Is this still happening or is it resolved?
